# Generated by Django 4.2 on 2023-05-05 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeEvaluacion',
            fields=[
                ('cod_evaluacion', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('nom_institucion', models.CharField(default=-1, max_length=40)),
                ('des_evaluacion', models.CharField(default=-1, max_length=20)),
            ],
            options={
                'db_table': 'axe_evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centro_Educativo',
            fields=[
                ('cod_identificador', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('cod_sace', models.CharField(default=-1, max_length=40)),
                ('nom_institucion', models.CharField(default=-1, max_length=20)),
                ('tip_categoria_institucion', models.CharField(default=-1, max_length=40)),
            ],
            options={
                'db_table': 'centro_educativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('cod_donacion', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('nom_institucion', models.CharField(default=-1, max_length=40)),
                ('tip_donacion', models.CharField(default=-1, max_length=40)),
                ('des_donacion', models.CharField(default=-1, max_length=40)),
                ('fec_donacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'donaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donantes',
            fields=[
                ('cod_donantes', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('cod_usuario', models.CharField(default=-1, max_length=20)),
                ('nombre', models.CharField(default=-1, max_length=100)),
                ('identidad', models.CharField(default=-1, max_length=15)),
                ('direccion', models.CharField(default=-1, max_length=50)),
                ('telefono', models.CharField(default=-1, max_length=20)),
                ('email', models.CharField(default=-1, max_length=50)),
                ('fec_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'donantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recuperar_Contrasenia',
            fields=[
                ('cod_pregunta_respuesta', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('cod_usuario', models.IntegerField()),
                ('nomb_pregunta', models.CharField(default=-1, max_length=200)),
                ('des_respuesta', models.CharField(default=-1, max_length=200)),
            ],
            options={
                'db_table': 'recuperar_contrasenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seg_Permisos',
            fields=[
                ('cod_permisos', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('per_insercion', models.CharField(default=-1, max_length=20)),
                ('per_eliminar', models.CharField(default=-1, max_length=20)),
                ('per_actualizar', models.CharField(default=-1, max_length=20)),
                ('per_consultar', models.CharField(default=-1, max_length=20)),
                ('fec_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_rol', models.IntegerField()),
            ],
            options={
                'db_table': 'seg_permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seg_Roles',
            fields=[
                ('cod_rol', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('tip_roles', models.CharField(default=-1, max_length=20)),
            ],
            options={
                'db_table': 'seg_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cod_usuario', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(default=-1, max_length=40)),
                ('contrasenia', models.CharField(default=-1, max_length=20)),
                ('estado_usuario', models.BooleanField(default=-1, max_length=20)),
                ('fec_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_rol', models.IntegerField()),
                ('telefono', models.CharField(default=-1, max_length=15)),
                ('email', models.CharField(default=-1, max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electrónico')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('image', models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen de perfil')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
